Client for cdbfefe2

diff --git a/bash/aicrowd-evaluations b/bash/aicrowd-evaluations
--- a/bash/aicrowd-evaluations
+++ b/bash/aicrowd-evaluations
@@ -141,6 +141,8 @@ operation_parameters_minimum_occurrences["listSubmissions:::status"]=0
 operation_parameters_minimum_occurrences["listSubmissions:::grader_id"]=0
 operation_parameters_minimum_occurrences["listSubmissions:::user_id"]=0
 operation_parameters_minimum_occurrences["listSubmissions:::X-Fields"]=0
+operation_parameters_minimum_occurrences["retrySubmissions:::payload"]=1
+operation_parameters_minimum_occurrences["retrySubmissions:::X-Fields"]=0
 operation_parameters_minimum_occurrences["createUser:::payload"]=1
 operation_parameters_minimum_occurrences["createUser:::X-Fields"]=0
 operation_parameters_minimum_occurrences["deleteUser:::user_id"]=1
@@ -206,6 +208,8 @@ operation_parameters_maximum_occurrences["listSubmissions:::status"]=0
 operation_parameters_maximum_occurrences["listSubmissions:::grader_id"]=0
 operation_parameters_maximum_occurrences["listSubmissions:::user_id"]=0
 operation_parameters_maximum_occurrences["listSubmissions:::X-Fields"]=0
+operation_parameters_maximum_occurrences["retrySubmissions:::payload"]=0
+operation_parameters_maximum_occurrences["retrySubmissions:::X-Fields"]=0
 operation_parameters_maximum_occurrences["createUser:::payload"]=0
 operation_parameters_maximum_occurrences["createUser:::X-Fields"]=0
 operation_parameters_maximum_occurrences["deleteUser:::user_id"]=0
@@ -268,6 +272,8 @@ operation_parameters_collection_type["listSubmissions:::status"]=""
 operation_parameters_collection_type["listSubmissions:::grader_id"]=""
 operation_parameters_collection_type["listSubmissions:::user_id"]=""
 operation_parameters_collection_type["listSubmissions:::X-Fields"]=""
+operation_parameters_collection_type["retrySubmissions:::payload"]=""
+operation_parameters_collection_type["retrySubmissions:::X-Fields"]=""
 operation_parameters_collection_type["createUser:::payload"]=""
 operation_parameters_collection_type["createUser:::X-Fields"]=""
 operation_parameters_collection_type["deleteUser:::user_id"]=""
@@ -704,6 +710,7 @@ read -r -d '' ops <<EOF
   ${CYAN}getSubmissionData${OFF}; (AUTH)
   ${CYAN}getSubmissionLogs${OFF}; (AUTH)
   ${CYAN}listSubmissions${OFF}; (AUTH)
+  ${CYAN}retrySubmissions${OFF}; (AUTH)
 EOF
 echo "  $ops" | column -t -s ';'
     echo ""
@@ -1287,6 +1294,28 @@ print_listSubmissions_help() {
     echo -e "${BOLD}${WHITE}Responses${OFF}"
     code=200
     echo -e "${result_color_table[${code:0:1}]}  200;Success${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+}
+##############################################################################
+#
+# Print help for retrySubmissions operation
+#
+##############################################################################
+print_retrySubmissions_help() {
+    echo ""
+    echo -e "${BOLD}${WHITE}retrySubmissions - ${OFF}${BLUE}(AUTH - HEADER)${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo -e "Retry the submissions with given IDs" | paste -sd' ' | fold -sw 80
+    echo -e ""
+    echo -e "${BOLD}${WHITE}Parameters${OFF}"
+    echo -e "  * ${GREEN}X-Fields${OFF} ${BLUE}[string]${OFF}${OFF} - An optional fields mask ${YELLOW}Specify as: X-Fields:value${OFF}" | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e "  * ${GREEN}body${OFF} ${BLUE}[application/json]${OFF} ${RED}(required)${OFF}${OFF} - " | paste -sd' ' | fold -sw 80 | sed '2,$s/^/    /'
+    echo -e ""
+    echo ""
+    echo -e "${BOLD}${WHITE}Responses${OFF}"
+    code=200
+    echo -e "${result_color_table[${code:0:1}]}  200;Success${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
+    code=404
+    echo -e "${result_color_table[${code:0:1}]}  404;Submission not found${OFF}" | paste -sd' ' | column -t -s ';' | fold -sw 80 | sed '2,$s/^/       /'
 }
 ##############################################################################
 #
@@ -2620,6 +2649,84 @@ call_listSubmissions() {
 
 ##############################################################################
 #
+# Call retrySubmissions operation
+#
+##############################################################################
+call_retrySubmissions() {
+    # ignore error about 'path_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local path_parameter_names=()
+    # ignore error about 'query_parameter_names' being unused; passed by reference
+    # shellcheck disable=SC2034
+    local query_parameter_names=(  )
+    local path
+
+    if ! path=$(build_request_path "/v1/submissions/retry" path_parameter_names query_parameter_names); then
+        ERROR_MSG=$path
+        exit 1
+    fi
+    local method="POST"
+    local headers_curl
+    headers_curl=$(header_arguments_to_curl)
+    if [[ -n $header_accept ]]; then
+        headers_curl="${headers_curl} -H 'Accept: ${header_accept}'"
+    fi
+
+    local basic_auth_option=""
+    if [[ -n $basic_auth_credential ]]; then
+        basic_auth_option="-u ${basic_auth_credential}"
+    fi
+    local body_json_curl=""
+
+    #
+    # Check if the user provided 'Content-type' headers in the
+    # command line. If not try to set them based on the Swagger specification
+    # if values produces and consumes are defined unambigously
+    #
+    if [[ -z $header_content_type ]]; then
+        header_content_type="application/json"
+    fi
+
+
+    if [[ -z $header_content_type && "$force" = false ]]; then
+        :
+        echo "ERROR: Request's content-type not specified!!!"
+        echo "This operation expects content-type in one of the following formats:"
+        echo -e "\\t- application/json"
+        echo ""
+        echo "Use '--content-type' to set proper content type"
+        exit 1
+    else
+        headers_curl="${headers_curl} -H 'Content-type: ${header_content_type}'"
+    fi
+
+
+    #
+    # If we have received some body content over pipe, pass it from the
+    # temporary file to cURL
+    #
+    if [[ -n $body_content_temp_file ]]; then
+        if [[ "$print_curl" = true ]]; then
+            echo "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        else
+            eval "cat ${body_content_temp_file} | curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} \"${host}${path}\" -d @-"
+        fi
+        rm "${body_content_temp_file}"
+    #
+    # If not, try to build the content body from arguments KEY==VALUE and KEY:=VALUE
+    #
+    else
+        body_json_curl=$(body_parameters_to_json)
+        if [[ "$print_curl" = true ]]; then
+            echo "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        else
+            eval "curl ${basic_auth_option} ${curl_arguments} ${headers_curl} -X ${method} ${body_json_curl} \"${host}${path}\""
+        fi
+    fi
+}
+
+##############################################################################
+#
 # Call createUser operation
 #
 ##############################################################################
@@ -3129,6 +3236,9 @@ case $key in
     listSubmissions)
     operation="listSubmissions"
     ;;
+    retrySubmissions)
+    operation="retrySubmissions"
+    ;;
     createUser)
     operation="createUser"
     ;;
@@ -3302,6 +3412,9 @@ case $operation in
     ;;
     listSubmissions)
     call_listSubmissions
+    ;;
+    retrySubmissions)
+    call_retrySubmissions
     ;;
     createUser)
     call_createUser
